# Generated by Django 4.2 on 2025-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sitesettings_site_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если указана и больше текущей цены, на сайте появится зачеркнутая цена и стикер SALE.', max_digits=10, null=True, verbose_name='Старая цена (для скидки)'),
        ),
    ]
