# Generated by Django 5.2.8 on 2025-11-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Стоимость доставки по городу')),
                ('pickup_address', models.TextField(blank=True, verbose_name='Адрес для самовывоза')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='График работы')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
