# Generated by Django 4.2 on 2025-12-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_sticker_color',
            field=models.CharField(blank=True, default='', help_text='HEX-код цвета (например, #FF0000). Если пусто, будет использоваться цвет из настроек сайта.', max_length=7, verbose_name='Цвет стикера скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price_color',
            field=models.CharField(blank=True, default='', help_text='HEX-код цвета новой цены при скидке. Если пусто, будет использоваться цвет из настроек сайта.', max_length=7, verbose_name='Цвет новой цены (при скидке)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_discount_sticker_color',
            field=models.CharField(blank=True, default='#e85454', help_text='Цвет по умолчанию для стикера скидки, если не указан в товаре.', max_length=7, verbose_name='Цвет стикера скидки (по умолчанию)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_new_price_color',
            field=models.CharField(blank=True, default='#e53935', help_text='Цвет по умолчанию для новой цены при скидке, если не указан в товаре.', max_length=7, verbose_name='Цвет новой цены (по умолчанию)'),
        ),
    ]
