# Generated by Django 5.2.8 on 2025-11-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение для баннера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для кнопки на баннере (URL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок на баннере'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок на баннере'),
        ),
    ]
