# Generated by Django 4.2 on 2025-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discount_sticker_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_sticker_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_price_color',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='discount_colors_mode',
            field=models.CharField(choices=[('individual', 'Индивидуальные цвета для каждого товара'), ('global', 'Общий цвет для всех товаров'), ('site_settings', 'Цвет из настроек сайта (акцентный)')], default='individual', help_text='Выберите, как будут применяться цвета скидок на сайте.', max_length=20, verbose_name='Режим цветов скидок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_discount_sticker_color',
            field=models.CharField(blank=True, default='#e85454', help_text="Используется в режимах: 'Общий цвет для всех товаров' и 'Цвет из настроек сайта'.", max_length=7, verbose_name='Цвет стикера скидки (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_new_price_color',
            field=models.CharField(blank=True, default='#e53935', help_text="Используется в режимах: 'Общий цвет для всех товаров' и 'Цвет из настроек сайта'.", max_length=7, verbose_name='Цвет новой цены (по умолчанию)'),
        ),
    ]
