# Generated by Django 5.2.8 on 2025-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, verbose_name="Текст для страницы 'О нас'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_text',
            field=models.TextField(blank=True, verbose_name="Текст для страницы 'Оплата'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_text',
            field=models.TextField(blank=True, verbose_name="Текст для страницы 'Договор оферты'"),
        ),
    ]
