# Generated by Django 4.2 on 2025-12-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_discount_sticker_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_sticker_color',
            field=models.CharField(blank=True, default='', help_text='HEX-код цвета (например, #FF0000). Если пусто, будет использоваться цвет из настроек сайта.', max_length=7, verbose_name='Цвет стикера скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price_color',
            field=models.CharField(blank=True, default='', help_text='HEX-код цвета новой цены при скидке. Если пусто, будет использоваться цвет из настроек сайта.', max_length=7, verbose_name='Цвет новой цены (при скидке)'),
        ),
    ]
