# Generated by Django 4.2 on 2025-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_discount_sticker_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='close_cutoff',
            field=models.PositiveIntegerField(default=20, help_text="За сколько минут до закрытия скрывать кнопку 'Как можно быстрее'.", verbose_name='Отсечка перед закрытием (мин)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_weekdays_close',
            field=models.TimeField(default='21:00', verbose_name='Закрытие (Пн-Пт) - Доставка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_weekdays_open',
            field=models.TimeField(default='09:00', verbose_name='Открытие (Пн-Пт) - Доставка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_weekend_close',
            field=models.TimeField(default='20:00', verbose_name='Закрытие (Сб-Вс) - Доставка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_weekend_open',
            field=models.TimeField(default='10:00', verbose_name='Открытие (Сб-Вс) - Доставка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='interval_step',
            field=models.PositiveIntegerField(default=120, help_text='Длительность слота доставки (120 мин = 2 часа).', verbose_name='Шаг интервала (мин)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='processing_time',
            field=models.PositiveIntegerField(default=50, help_text='За сколько минут до начала интервала блокировать заказ. (Пример: 50 мин)', verbose_name='Время на сборку (мин)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_weekdays_close',
            field=models.TimeField(default='21:00', verbose_name='Закрытие (Пн-Пт) - Магазин'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_weekdays_open',
            field=models.TimeField(default='09:00', verbose_name='Открытие (Пн-Пт) - Магазин'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_weekend_close',
            field=models.TimeField(default='20:00', verbose_name='Закрытие (Сб-Вс) - Магазин'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_weekend_open',
            field=models.TimeField(default='10:00', verbose_name='Открытие (Сб-Вс) - Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_sticker_color',
            field=models.CharField(blank=True, default='', help_text='HEX-код цвета (например, #FF0000). Если пусто(все нули), будет использоваться цвет из настроек сайта.', max_length=7, verbose_name='Цвет стикера скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price_color',
            field=models.CharField(blank=True, default='', help_text='HEX-код цвета новой цены при скидке. Если пусто(000000), будет использоваться цвет из Настроек сайта (Цвета скидок глобальные).', max_length=7, verbose_name='Цвет новой цены (при скидке)'),
        ),
    ]
