# Generated by Django 5.2.8 on 2025-11-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sitesettings_about_text_sitesettings_payment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shop_name',
            field=models.CharField(default='MegaCvet', max_length=100, verbose_name='Название магазина'),
        ),
    ]
