# Generated by Django 5.2.8 on 2025-11-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_sitesettings_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_title',
            field=models.CharField(default='О нас', max_length=50, verbose_name="Название ссылки 'О нас'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contacts_title',
            field=models.CharField(default='Контакты', max_length=50, verbose_name="Название ссылки 'Контакты'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_payment_title',
            field=models.CharField(default='Оплата', max_length=50, verbose_name="Название ссылки 'Оплата'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_terms_title',
            field=models.CharField(default='Договор оферты', max_length=50, verbose_name="Название ссылки 'Договор оферты'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=10, verbose_name='Стоимость доставки по городу'),
        ),
    ]
