# Generated by Django 5.2.8 on 2025-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sitesettings_footer_about_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ссылки')),
                ('url', models.CharField(max_length=200, verbose_name='URL-адрес (например, /about/ или /contacts/)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем левее ссылка', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_about_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_contacts_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_payment_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_terms_title',
        ),
    ]
