# Generated by Django 4.2 on 2025-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sitesettings_enable_admin_autosave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_admin_autosave',
            field=models.BooleanField(default=False, help_text="Если включено, изменение статуса в таблице заказов сохраняется мгновенно без нажатия кнопки 'Сохранить'.", verbose_name='Включить автосохранение'),
        ),
    ]
