# Generated by Django 4.2 on 2025-12-03 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_sitesettings_enable_admin_autosave'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slider_desktop_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (Обрезать края)'), ('contain', 'Вписать целиком (С полями)')], default='cover', help_text='Cover: Красиво, но края обрезаются. Contain: Видно всё, но могут быть полосы.', max_length=10, verbose_name='Режим на ПК'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider_height_desktop',
            field=models.PositiveIntegerField(default=550, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1000)], verbose_name='Высота на ПК (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider_height_mobile',
            field=models.PositiveIntegerField(default=350, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(700)], verbose_name='Высота на Мобильном (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider_mobile_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (Обрезать края)'), ('contain', 'Вписать целиком (С полями)')], default='cover', max_length=10, verbose_name='Режим на Мобильном'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_duration',
            field=models.PositiveIntegerField(default=5, verbose_name='Длительность слайда (сек)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_effect',
            field=models.CharField(choices=[('slide', 'Пролистывание (Slide)'), ('fade', 'Наплыв (Fade)'), ('cube', '3D Куб (Cube)'), ('flip', '3D Переворот (Flip)'), ('coverflow', '3D Карусель (Coverflow)'), ('cards', 'Карточки (Стопкой)'), ('creative_one', 'Креативный (Перспектива)'), ('creative_two', 'Креативный (Сдвиг справа)'), ('creative_three', 'Креативный (Вращение)'), ('fade_zoom', 'Наплыв с зумом (Fade Zoom)'), ('parallax', 'Параллакс (Parallax)'), ('kenburns', 'Кен Бернс (Медленное приближение)')], default='slide', max_length=20, verbose_name='Эффект перехода'),
        ),
    ]
