# Generated by Django 5.2.8 on 2025-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_footerlink_remove_sitesettings_footer_about_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ссылки и заголовок страницы')),
                ('slug', models.SlugField(help_text="Только английские буквы, цифры и дефисы. Например, 'about-us'", unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое страницы')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем левее ссылка', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страница в футере',
                'verbose_name_plural': 'Страницы в футере',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='payment_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='terms_text',
        ),
    ]
