# Generated by Django 4.2 on 2025-12-03 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sitesettings_slider_desktop_fit_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='base_font_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='body_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='main_text_color',
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона текста'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст на кнопке (необязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (всплывашка)'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon_svg',
            field=models.TextField(verbose_name='SVG иконка'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition_title',
            field=models.CharField(blank=True, max_length=100, verbose_name="Заголовок для 'Состава'"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_title',
            field=models.CharField(blank=True, max_length=100, verbose_name="Заголовок для 'Описания'"),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_sticker_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет стикера скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет новой цены (при скидке)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (для скидки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_hover_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name="Цвет фона 'В корзину' при наведении"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name="Цвет текста кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, verbose_name='Email для уведомлений (Админ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_accent_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Акцентный цвет КНОПОК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет фона при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='catalog_title_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет заголовка каталога'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста (Меню категорий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='close_cutoff',
            field=models.PositiveIntegerField(default=20, verbose_name="Блокировка 'Как можно быстрее' (мин)"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для клиентов (Публичный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_discount_sticker_color',
            field=models.CharField(blank=True, default='#e85454', max_length=7, verbose_name='Цвет стикера скидки (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_new_price_color',
            field=models.CharField(blank=True, default='#e53935', max_length=7, verbose_name='Цвет новой цены (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_text_color',
            field=models.CharField(blank=True, default='#333333', max_length=7, verbose_name='Цвет шрифта (Основной)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_weekdays_close',
            field=models.TimeField(default='23:00', verbose_name='Доставка: Конец (Пн-Пт)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_weekdays_open',
            field=models.TimeField(default='09:00', verbose_name='Доставка: Начало (Пн-Пт)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_weekend_close',
            field=models.TimeField(default='22:00', verbose_name='Доставка: Конец (Сб-Вс)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_weekend_open',
            field=models.TimeField(default='10:00', verbose_name='Доставка: Начало (Сб-Вс)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Свой цвет Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_opacity',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='Прозрачность Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_category_blur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размытие Категорий (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_blur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размытие Шапки (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, null=True, verbose_name='Прозрачность Шапки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='discount_colors_mode',
            field=models.CharField(choices=[('individual', 'Индивидуальные'), ('global', 'Общий цвет'), ('site_settings', 'Цвет из настроек')], default='individual', max_length=20, verbose_name='Режим цветов скидок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_admin_autosave',
            field=models.BooleanField(default=False, verbose_name='Включить автосохранение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста (Подвал)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='montserrat', max_length=50, verbose_name='Шрифт для заголовков (H1, H2...)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_animation_style',
            field=models.CharField(choices=[('scale', 'Увеличение (стандарт)'), ('rotate', 'Вращение'), ('bounce', 'Подпрыгивание'), ('shake', 'Тряска (Shake)'), ('pulse', 'Пульсация (Pulse)'), ('swing', 'Качание (Swing)')], default='scale', max_length=10, verbose_name='СТИЛЬ АНИМАЦИИ ИКОНОК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет иконок (Шапка)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='interval_step',
            field=models.PositiveIntegerField(default=120, verbose_name='Шаг интервала доставки (мин)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип (Изображение)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, verbose_name='HTML-код карты'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет фона кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скругление кнопок (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(blank=True, default=100, null=True, verbose_name='Прозрачность кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_inherit_radius',
            field=models.BooleanField(default=True, verbose_name='Использовать глобальное скругление?'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(blank=True, default=95, null=True, verbose_name='Прозрачность фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_bg_color_custom',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Свой цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_blur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размытие (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, null=True, verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navigation_style',
            field=models.CharField(choices=[('underline', 'Анимация подчеркивания'), ('highlight', 'Фоновая подсветка'), ('lift', 'Эффект приподнимания'), ('shadow', 'Сдвиг с тенью (3D)'), ('wave', '"Жидкая" волна')], default='underline', max_length=10, verbose_name='Стиль анимации навигации'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='order_start_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Начальный номер ЗАКАЗА'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='pickup_address',
            field=models.TextField(blank=True, verbose_name='Адрес самовывоза'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popular_title_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет заголовка (Популярные)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='processing_time',
            field=models.PositiveIntegerField(default=50, verbose_name='Время на сборку (мин)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста (Заголовки описания)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста (Название товара)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_bg_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Фон листа сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_blur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размытие фона листа (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_opacity',
            field=models.FloatField(blank=True, default=95, null=True, verbose_name='Прозрачность листа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sku_start_number',
            field=models.PositiveIntegerField(default=11287, verbose_name='Начальный АРТИКУЛ товара'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_desktop_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (Обрезать края)'), ('contain', 'Вписать целиком (С полями)')], default='cover', help_text='Cover: Обрезать края. Contain: Вписать целиком.', max_length=10, verbose_name='Режим на ПК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_effect',
            field=models.CharField(choices=[('slide', 'Пролистывание (Slide)'), ('fade', 'Наплыв (Fade)'), ('cube', '3D Куб (Cube)'), ('coverflow', '3D Карусель (Coverflow)'), ('flip', '3D Переворот (Flip)'), ('cards', 'Карточки (Cards)'), ('creative', 'Креативный (Creative)'), ('fade_zoom', 'Наплыв с зумом (Fade Zoom)'), ('parallax', 'Параллакс (Parallax)'), ('kenburns', 'Кен Бернс (Медленное приближение)')], default='slide', max_length=20, verbose_name='Эффект перехода'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_icon_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет иконок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_link_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет ссылок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_link_hover_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет ссылок при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_subtitle_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет подзаголовков H3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_title_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет заголовков H1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='work_weekdays_close',
            field=models.TimeField(default='21:00', verbose_name='Магазин: Закрытие (Пн-Пт)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='work_weekdays_open',
            field=models.TimeField(default='09:00', verbose_name='Магазин: Открытие (Пн-Пт)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='work_weekend_close',
            field=models.TimeField(default='20:00', verbose_name='Магазин: Закрытие (Сб-Вс)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='work_weekend_open',
            field=models.TimeField(default='10:00', verbose_name='Магазин: Открытие (Сб-Вс)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.TextField(blank=True, verbose_name='Режим работы (Текст)'),
        ),
    ]
