# Generated by Django 5.2.8 on 2025-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_footerpage_delete_footerlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpage',
            name='page_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название ссылки', max_length=200, verbose_name='Заголовок на странице'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название ссылки'),
        ),
    ]
