# Generated by Django 4.2 on 2025-12-03 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_sitesettings_base_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_desktop_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (Обрезать края)'), ('contain', 'Вписать целиком (С полями)'), ('auto', 'Адаптивно (По высоте картинки)')], default='cover', help_text='Cover: Обрезать края. Contain: Вписать целиком.', max_length=10, verbose_name='Режим на ПК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_height_desktop',
            field=models.PositiveIntegerField(default=550, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1200)], verbose_name='Высота на ПК (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_height_mobile',
            field=models.PositiveIntegerField(default=350, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(700)], verbose_name='Высота на Мобильном (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_mobile_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (Обрезать края)'), ('contain', 'Вписать целиком (С полями)'), ('auto', 'Адаптивно (По высоте картинки)')], default='cover', max_length=10, verbose_name='Режим на Мобильном'),
        ),
    ]
