# Generated by Django 4.2 on 2025-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_sitesettings_slider_desktop_fit_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_desktop_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (В поле установка(высота) Обрезать края)'), ('contain', 'Вписать целиком (В поле установка(высота) без обрезаний )'), ('auto', 'Адаптивно (По высоте самой высокой картинки растягивает)')], default='cover', help_text='Cover: Обрезать края. Contain: Вписать целиком.', max_length=10, verbose_name='Режим на ПК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_mobile_fit_mode',
            field=models.CharField(choices=[('cover', 'Заполнить (В поле установка(высота) Обрезать края)'), ('contain', 'Вписать целиком (В поле установка(высота) без обрезаний )'), ('auto', 'Адаптивно (По высоте самой высокой картинки растягивает)')], default='cover', max_length=10, verbose_name='Режим на Мобильном'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.TextField(blank=True, verbose_name='Режим работы (Основное время в настройке - Время работы и интервалы, тут можно просто дополнить)'),
        ),
    ]
