# Generated by Django 5.2.8 on 2025-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Введите email-адреса через запятую, на которые будут приходить уведомления о новых заказах.', verbose_name='Email для уведомлений о заказах'),
        ),
    ]
