# Generated by Django 4.2 on 2025-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_footerpage_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_postcard_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Если 0, то бесплатно.', max_digits=10, verbose_name="Цена за печать 'Своего фото'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='close_cutoff',
            field=models.PositiveIntegerField(default=20, verbose_name="Блокировка 'Как можно быстрее' до закрытия  (мин)"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='processing_time',
            field=models.PositiveIntegerField(default=50, verbose_name='Время на сборку до интервала (мин)'),
        ),
    ]
