# Generated by Django 5.2.8 on 2025-11-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_sitesettings_admin_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Если не выбрано, будет использоваться фон по умолчанию из static/shop/img/background.jpg', null=True, upload_to='backgrounds/', verbose_name='Фоновое изображение сайта'),
        ),
    ]
