# Generated by Django 4.2 on 2025-12-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_sitesettings_custom_postcard_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slider_width_mode',
            field=models.CharField(choices=[('boxed', 'Внутри контейнера (с отступами)'), ('sheet', 'По ширине листа (от края до края листа)'), ('full', 'Во весь экран (100% ширины монитора)')], default='sheet', help_text='Full: Картинка растянется на весь монитор (нужны фото высокого качества 2K/4K).', max_length=10, verbose_name='Ширина слайдера'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_height_desktop',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1200)], verbose_name='Высота на ПК (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_height_mobile',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(700)], verbose_name='Высота на Мобильном (px)'),
        ),
    ]
