# Generated by Django 4.2 on 2025-12-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_sitesettings_slider_width_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
