# Generated by Django 5.2.8 on 2025-11-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_bottom',
            field=models.TextField(blank=True, verbose_name='Состав (под фото)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_right',
            field=models.TextField(blank=True, verbose_name='Описание (справа от фото)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_description_bottom_title',
            field=models.CharField(default='Состав', max_length=100, verbose_name='Заголовок описания (внизу)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_description_right_title',
            field=models.CharField(default='Описание', max_length=100, verbose_name='Заголовок описания (справа)'),
        ),
    ]
