# Generated by Django 5.2.8 on 2025-11-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_bottom',
            field=models.TextField(blank=True, verbose_name='Текстовый блок (под фото)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_right',
            field=models.TextField(blank=True, verbose_name='Текстовый блок (справа от фото)'),
        ),
    ]
