# Generated by Django 5.2.8 on 2025-11-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_description_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_bottom_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использован заголовок из Настроек сайта.', max_length=100, verbose_name='Заголовок блока внизу'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_right_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использован заголовок из Настроек сайта.', max_length=100, verbose_name='Заголовок блока справа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_description_bottom_title',
            field=models.CharField(default='Состав', max_length=100, verbose_name='Заголовок описания (внизу) ПО УМОЛЧАНИЮ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_description_right_title',
            field=models.CharField(default='Описание', max_length=100, verbose_name='Заголовок описания (справа) ПО УМОЛЧАНИЮ'),
        ),
    ]
