# Generated by Django 5.2.8 on 2025-11-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_description_bottom_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_bottom_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использован заголовок из Настроек сайта.', max_length=100, verbose_name='Уникальный заголовок блока внизу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_right_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использован заголовок из Настроек сайта.', max_length=100, verbose_name='Уникальный заголовок блока справа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_description_bottom_title',
            field=models.CharField(default='Состав', max_length=100, verbose_name='Заголовок блока внизу (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_description_right_title',
            field=models.CharField(default='Описание', max_length=100, verbose_name='Заголовок блока справа (по умолчанию)'),
        ),
    ]
