# Generated by Django 5.2.8 on 2025-11-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_description_bottom_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка для кнопки (URL)')),
                ('is_active', models.BooleanField(default=True, help_text='Только активные баннеры будут показаны на сайте.', verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше баннер в очереди.', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider_duration',
            field=models.PositiveIntegerField(default=5, help_text='Укажите, через сколько секунд слайды будут меняться автоматически.', verbose_name='Пауза между слайдами (в секундах)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slider_effect',
            field=models.CharField(choices=[('slide', 'Пролистывание'), ('fade', 'Наплыв (исчезание/появление)'), ('cube', '3D Куб'), ('flip', '3D Переворот')], default='slide', max_length=10, verbose_name='Эффект смены слайдов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Введите email-адреса через запятую...', verbose_name='Email для уведомлений о заказах'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Если не выбрано, будет фон по умолчанию...', null=True, upload_to='backgrounds/', verbose_name='Фоновое изображение сайта'),
        ),
    ]
