# Generated by Django 5.2.8 on 2025-11-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_banner_remove_sitesettings_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Только активные баннеры будут показаны.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка (URL)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок на странице'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, verbose_name='Email для уведомлений'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_description_bottom_title',
            field=models.CharField(default='Состав', max_length=100, verbose_name='Заголовок блока внизу (по умолч.)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_description_right_title',
            field=models.CharField(default='Описание', max_length=100, verbose_name='Заголовок блока справа (по умолч.)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_duration',
            field=models.PositiveIntegerField(default=5, verbose_name='Пауза между слайдами (сек)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_effect',
            field=models.CharField(choices=[('slide', 'Пролистывание'), ('fade', 'Наплыв'), ('cube', '3D Куб'), ('flip', '3D Переворот')], default='slide', max_length=10, verbose_name='Эффект смены слайдов'),
        ),
    ]
