# Generated by Django 5.2.8 on 2025-11-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_banner_is_active_alter_banner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Если поле пустое, весь баннер будет ссылкой.', max_length=50, verbose_name='Текст на кнопке (необязательно)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_position',
            field=models.CharField(choices=[('center-center', 'По центру'), ('bottom-left', 'Внизу слева'), ('bottom-right', 'Внизу справа'), ('top-left', 'Вверху слева'), ('top-right', 'Вверху справа')], default='center-center', max_length=20, verbose_name='Расположение текста'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Изображение (1600x600)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка (URL, необязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок (необязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)'),
        ),
    ]
