# Generated by Django 5.2.8 on 2025-11-14 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_banner_button_text_banner_content_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=45, help_text='От 0 (полностью прозрачный) до 100 (непрозрачный).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона текста (%)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='font_color',
            field=models.CharField(default='#FFFFFF', help_text='В формате HEX, например, #FFFFFF для белого.', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AddField(
            model_name='banner',
            name='font_family',
            field=models.CharField(choices=[('sans-serif', 'Стандартный (Roboto)'), ('serif', 'С засечками (Lora)'), ('cursive', 'Декоративный (Lobster)')], default='sans-serif', max_length=20, verbose_name='Стиль шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(default='#333333', help_text='В формате HEX, например, #333333.', max_length=7, verbose_name='Цвет названия магазина'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(default=28, help_text='Укажите размер в пикселях.', verbose_name='Размер шрифта названия (px)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Если пусто, весь баннер будет ссылкой.', max_length=50, verbose_name='Текст на кнопке (необязательно)'),
        ),
    ]
