# Generated by Django 5.2.8 on 2025-11-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_banner_background_opacity_banner_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(choices=[('sans-serif', 'Стандартный (Roboto)'), ('serif', 'С засечками (Lora)'), ('cursive', 'Декоративный (Lobster)')], default='sans-serif', max_length=20, verbose_name='Стиль шрифта названия'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(default='#333333', help_text='В формате HEX.', max_length=7, verbose_name='Цвет названия магазина'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(default=28, verbose_name='Размер шрифта названия (px)'),
        ),
    ]
