# Generated by Django 5.2.8 on 2025-11-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_sitesettings_logo_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e53935', max_length=7, verbose_name='Акцентный цвет (ссылки, кнопки)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='base_font_size',
            field=models.PositiveIntegerField(default=16, verbose_name='Базовый размер шрифта (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='body_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный без засечек (Roboto)'), ('montserrat', 'Современный без засечек (Montserrat)'), ('open-sans', 'Дружелюбный без засечек (Open Sans)'), ('lora', 'Элегантный с засечками (Lora)'), ('merriweather', 'Классический с засечками (Merriweather)'), ('playfair-display', 'Журнальный с засечками (Playfair Display)'), ('lobster', 'Декоративный рукописный (Lobster)'), ('pacifico', 'Мягкий рукописный (Pacifico)')], default='roboto', max_length=50, verbose_name='Шрифт для основного текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный без засечек (Roboto)'), ('montserrat', 'Современный без засечек (Montserrat)'), ('open-sans', 'Дружелюбный без засечек (Open Sans)'), ('lora', 'Элегантный с засечками (Lora)'), ('merriweather', 'Классический с засечками (Merriweather)'), ('playfair-display', 'Журнальный с засечками (Playfair Display)'), ('lobster', 'Декоративный рукописный (Lobster)'), ('pacifico', 'Мягкий рукописный (Pacifico)')], default='montserrat', max_length=50, verbose_name='Шрифт для заголовков'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_text_color',
            field=models.CharField(default='#333333', max_length=7, verbose_name='Основной цвет текста'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный без засечек (Roboto)'), ('montserrat', 'Современный без засечек (Montserrat)'), ('open-sans', 'Дружелюбный без засечек (Open Sans)'), ('lora', 'Элегантный с засечками (Lora)'), ('merriweather', 'Классический с засечками (Merriweather)'), ('playfair-display', 'Журнальный с засечками (Playfair Display)'), ('lobster', 'Декоративный рукописный (Lobster)'), ('pacifico', 'Мягкий рукописный (Pacifico)')], default='roboto', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный без засечек (Roboto)'), ('montserrat', 'Современный без засечек (Montserrat)'), ('open-sans', 'Дружелюбный без засечек (Open Sans)'), ('lora', 'Элегантный с засечками (Lora)'), ('merriweather', 'Классический с засечками (Merriweather)'), ('playfair-display', 'Журнальный с засечками (Playfair Display)'), ('lobster', 'Декоративный рукописный (Lobster)'), ('pacifico', 'Мягкий рукописный (Pacifico)')], default='roboto', max_length=50, verbose_name='Стиль шрифта названия'),
        ),
    ]
