# Generated by Django 5.2.8 on 2025-11-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_hover_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет при наведении'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер шрифта (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_price_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет цены'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_title_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет названия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт названия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_title_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер названия (px)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='roboto', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='body_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='roboto', max_length=50, verbose_name='Шрифт для основного текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='montserrat', max_length=50, verbose_name='Шрифт для заголовков'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, help_text='Пусто = глобальный цвет', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто = по умолчанию', null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_duration',
            field=models.PositiveIntegerField(default=5, verbose_name='Пауза (сек)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_effect',
            field=models.CharField(choices=[('slide', 'Пролистывание'), ('fade', 'Наплыв'), ('cube', '3D Куб'), ('flip', '3D Переворот')], default='slide', max_length=10, verbose_name='Эффект'),
        ),
    ]
