# Generated by Django 5.2.8 on 2025-11-14 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_sitesettings_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='add_text_shadow',
            field=models.BooleanField(default=True, help_text='Улучшает читаемость.', verbose_name='Добавить тень к тексту'),
        ),
        migrations.AddField(
            model_name='banner',
            name='background_border_radius',
            field=models.PositiveIntegerField(default=8, verbose_name='Скругление углов фона (px)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(default='#333333', max_length=7, verbose_name='Цвет текста на кнопке'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_font_size',
            field=models.PositiveIntegerField(default=20, verbose_name='Размер подзаголовка (px)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_font_size',
            field=models.PositiveIntegerField(default=45, verbose_name='Размер заголовка (px)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона (%)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Если пусто, весь баннер будет ссылкой.', max_length=50, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка (URL)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта названия'),
        ),
    ]
