# Generated by Django 5.2.8 on 2025-11-14 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_banner_add_text_shadow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='add_text_shadow',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_border_radius',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_font_size',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_font_size',
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=45, help_text='От 0 (полностью прозрачный) до 100 (непрозрачный).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона текста (%)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Если пусто, весь баннер будет ссылкой.', max_length=50, verbose_name='Текст на кнопке (необязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_color',
            field=models.CharField(default='#FFFFFF', help_text='В формате HEX, например, #FFFFFF для белого.', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Только активные баннеры будут показаны.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка (URL, необязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок (необязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (необязательно)'),
        ),
    ]
