# Generated by Django 5.2.8 on 2025-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_banner_add_text_shadow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=300.0, help_text='Стоимость доставки будет добавлена к общей сумме заказа.', max_digits=10, verbose_name='Стоимость доставки'),
        ),
    ]
