# Generated by Django 5.2.8 on 2025-11-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_sitesettings_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, help_text='Пусто = акцентный цвет', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто = 5px', null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text='Пусто = шрифт основного текста', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, help_text='Пусто = темно-серый (#333)', max_length=7, verbose_name='Цвет фона при наведении'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(blank=True, help_text='Пусто = белый', max_length=7, verbose_name='Цвет текста'),
        ),
    ]
