# Generated by Django 5.2.8 on 2025-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_sitesettings_button_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, help_text='Если пусто, используется основной цвет кнопок.', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='add_to_cart_hover_bg_color',
            field=models.CharField(blank=True, help_text='Если пусто, используется основной цвет кнопок при наведении.', max_length=7, verbose_name="Цвет фона 'В корзину' при наведении"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='add_to_cart_text_color',
            field=models.CharField(blank=True, help_text='Если пусто, используется основной цвет текста кнопок.', max_length=7, verbose_name="Цвет текста кнопки 'В корзину'"),
        ),
    ]
