# Generated by Django 5.2.8 on 2025-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_sitesettings_add_to_cart_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_bottom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_bottom_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_right',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_right_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_description_bottom_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_description_right_title',
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав (блок под фото)'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition_title',
            field=models.CharField(blank=True, help_text='Если пусто, будет использован заголовок из Настроек сайта.', max_length=100, verbose_name="Заголовок для 'Состава'"),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (блок справа от фото)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_title',
            field=models.CharField(blank=True, help_text='Если пусто, будет использован заголовок из Настроек сайта.', max_length=100, verbose_name="Заголовок для 'Описания'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_composition_title',
            field=models.CharField(default='Состав', max_length=100, verbose_name="Заголовок 'Состава' (по умолч.)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_description_title',
            field=models.CharField(default='Описание', max_length=100, verbose_name="Заголовок 'Описания' (по умолч.)"),
        ),
    ]
