# Generated by Django 5.2.8 on 2025-11-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_product_description_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navigation_style',
            field=models.CharField(choices=[('underline', 'Анимация подчеркивания'), ('highlight', 'Фоновая подсветка'), ('lift', 'Эффект приподнимания')], default='underline', help_text='Выберите эффект, который будет применяться при наведении на ссылки в шапке, меню категорий и подвале.', max_length=10, verbose_name='Стиль анимации навигации'),
        ),
    ]
