# Generated by Django 5.2.8 on 2025-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_sitesettings_navigation_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='navigation_style',
            field=models.CharField(choices=[('underline', 'Анимация подчеркивания'), ('highlight', 'Фоновая подсветка'), ('lift', 'Эффект приподнимания'), ('shadow', 'Сдвиг с тенью (3D)'), ('wave', '"Жидкая" волна')], default='underline', help_text='Выберите эффект, который будет применяться при наведении на ссылки в шапке, меню категорий и подвале.', max_length=10, verbose_name='Стиль анимации навигации'),
        ),
    ]
