# Generated by Django 5.2.8 on 2025-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_sitesettings_navigation_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='На мобильных устройствах, если категорий больше этого числа, они скроются под иконку-бургер.', verbose_name='Схлопывать категории в иконку, если их больше чем'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text="На мобильных, если ссылок в футере больше этого числа, они скроются под иконку 'еще'.", verbose_name='Схлопывать ссылки в подвале, если их больше чем'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('full', 'Иконки и полный текст (как на десктопе)'), ('partial', 'Иконки и короткий текст (Кабинет, Корзина)'), ('icons', 'Только иконки')], default='partial', max_length=10, verbose_name='Стиль шапки на мобильных'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки (для планшетов)')], default=2, verbose_name='Кол-во товаров в ряду на мобильных'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navigation_style',
            field=models.CharField(choices=[('underline', 'Анимация подчеркивания'), ('highlight', 'Фоновая подсветка'), ('lift', 'Эффект приподнимания'), ('shadow', 'Сдвиг с тенью (3D)'), ('wave', '"Жидкая" волна')], default='underline', help_text='Эффект при наведении на ссылки в меню.', max_length=10, verbose_name='Стиль анимации навигации'),
        ),
    ]
