# Generated by Django 5.2.8 on 2025-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_sitesettings_collapse_categories_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктопе (без изменений)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки (для планшетов)')], default=2, verbose_name='Кол-во товаров в ряду на мобильных'),
        ),
    ]
