# Generated by Django 5.2.8 on 2025-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_sitesettings_mobile_product_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Цвет фона для выпадающего меню категорий и поиска на мобильных.', max_length=7, verbose_name='Фон выпадающих меню (моб. версия)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('full', 'Иконки и полный текст (как на десктопе)'), ('partial', 'Иконки и короткий текст (Кабинет, Корзина)'), ('icons', 'Только иконки')], default='partial', max_length=10, verbose_name='Отображение ссылок в шапке (моб. версия)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктопе (адаптивно)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки (для планшетов)')], default=2, verbose_name='Кол-во товаров в ряду (моб. версия)'),
        ),
    ]
