# Generated by Django 5.2.8 on 2025-11-16 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_sitesettings_mobile_dropdown_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=95, help_text='От 0 (полностью прозрачный) до 100 (непрозрачный).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона выпадающих меню (%)'),
        ),
    ]
