# Generated by Django 5.2.8 on 2025-11-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_sitesettings_mobile_dropdown_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_icon_size',
            field=models.PositiveSmallIntegerField(default=22, help_text="Размер иконок 'Кабинет', 'Корзина', 'Поиск', 'Категории' на десктопе.", verbose_name='Размер иконок в шапке (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_icon_size',
            field=models.PositiveSmallIntegerField(default=24, help_text='Увеличенный размер иконок для удобства нажатия на мобильных.', verbose_name='Размер иконок в шапке (моб. версия, px)'),
        ),
    ]
