# Generated by Django 5.2.8 on 2025-11-16 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_sitesettings_header_icon_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_force_desktop_view',
            field=models.BooleanField(default=False, help_text='Если включено, сайт на мобильных устройствах не будет адаптироваться, а покажет полную версию, которую можно масштабировать.', verbose_name='Принудительный десктопный вид на мобильных'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=45, help_text='От 0 (полностью прозрачный) до 100 (непрозрачный).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона выпадающих меню (%)'),
        ),
    ]
