# Generated by Django 5.2.8 on 2025-11-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_sitesettings_mobile_force_desktop_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного фона.', max_length=7, verbose_name='Цвет фона шапки (десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_link_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного цвета.', max_length=7, verbose_name='Цвет ссылок в шапке (десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного фона.', max_length=7, verbose_name='Цвет фона шапки (моб. версия)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_link_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного цвета.', max_length=7, verbose_name='Цвет ссылок в шапке (моб. версия)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_view_mode',
            field=models.CharField(choices=[('adaptive', 'Адаптивный вид (стандарт)'), ('desktop_full', 'Принудительный десктопный вид (с текстом)'), ('desktop_icons', 'Принудительный десктопный вид (только иконки)')], default='adaptive', help_text='Выберите, как сайт будет выглядеть на смартфонах.', max_length=15, verbose_name='Режим отображения на мобильных'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='В адаптивном режиме, если категорий больше этого числа, они скроются под иконку-бургер.', verbose_name='Схлопывать категории в иконку, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='В адаптивном режиме, если ссылок в футере больше этого числа, они скроются.', verbose_name='Схлопывать ссылки в подвале, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Цвет фона для выпадающего меню категорий и поиска.', max_length=7, verbose_name='Фон выпадающих меню (моб. версия)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('full', 'Иконки и полный текст'), ('partial', 'Иконки и короткий текст'), ('icons', 'Только иконки')], default='partial', max_length=10, verbose_name='Отображение ссылок в шапке (в адаптивном режиме)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктопе (адаптивно)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки (для планшетов)')], default=2, verbose_name='Кол-во товаров в ряду (в адаптивном режиме)'),
        ),
    ]
