# Generated by Django 5.2.8 on 2025-11-17 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_sitesettings_header_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='header_icon_size',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='Размер иконок в шапке (десктоп, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=95, help_text='От 0 до 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона выпадающих меню (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_icon_size',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='Размер иконок в шапке (моб. версия, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктоpe (адаптивно)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, verbose_name='Кол-во товаров в ряду (в адаптивном режиме)'),
        ),
    ]
