# Generated by Django 5.2.8 on 2025-11-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_sitesettings_mobile_dropdown_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_force_desktop_view',
        ),
    ]
