# Generated by Django 5.2.8 on 2025-11-18 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_sitesettings_mobile_force_desktop_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_font_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_font_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_hover_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_font_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_font_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_icon_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_link_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_header_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_header_link_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_icon_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_price_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_title_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_title_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_title_font_size',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, help_text='Пусто = основной цвет кнопок сайта', max_length=7, verbose_name='Цвет фона кнопок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто = основное скругление', null=True, verbose_name='Скругление кнопок (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(default=100, help_text='От 0 до 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, help_text='Пусто = основной цвет текста кнопок', max_length=7, verbose_name='Цвет текста кнопок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, help_text='Пусто = основной цвет текста сайта', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text='Пусто = шрифт основного текста сайта', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Пусто = базовый размер', null=True, verbose_name='Размер шрифта (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='Только для адаптивного режима.', verbose_name='Схлопывать категории в иконку, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='Только для адаптивного режима.', verbose_name='Схлопывать ссылки в подвале, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('full', 'Иконки и полный текст'), ('partial', 'Иконки и короткий текст'), ('icons', 'Только иконки')], default='partial', help_text='Только для адаптивного режима.', max_length=10, verbose_name='Отображение ссылок в шапке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктоpe (адаптивно)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, help_text='Только для адаптивного режима.', verbose_name='Кол-во товаров в ряду'),
        ),
    ]
