# Generated by Django 5.2.8 on 2025-11-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_remove_sitesettings_category_nav_font_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_dropdown_font_size',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_nav_hover_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет при наведении'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер шрифта (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного фона.', max_length=7, verbose_name='Цвет фона шапки (десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_icon_size',
            field=models.PositiveSmallIntegerField(default=22, verbose_name='Размер иконок в шапке (десктоп, px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_link_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного цвета.', max_length=7, verbose_name='Цвет ссылок в шапке (десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного фона.', max_length=7, verbose_name='Цвет фона шапки (моб. версия)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_link_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым для стандартного цвета.', max_length=7, verbose_name='Цвет ссылок в шапке (моб. версия)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_icon_size',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='Размер иконок в шапке (моб. версия, px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_price_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет цены'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_title_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет названия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт названия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_card_title_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер названия (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='В адаптивном режиме, если категорий больше этого числа, они скроются под иконку-бургер.', verbose_name='Схлопывать категории в иконку, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='В адаптивном режиме, если ссылок в футере больше этого числа, они скроются.', verbose_name='Схлопывать ссылки в подвале, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('full', 'Иконки и полный текст'), ('partial', 'Иконки и короткий текст'), ('icons', 'Только иконки')], default='partial', max_length=10, verbose_name='Отображение ссылок в шапке (в адаптивном режиме)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктоpe (адаптивно)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, verbose_name='Кол-во товаров в ряду (в адаптивном режиме)'),
        ),
    ]
