# Generated by Django 5.2.8 on 2025-11-18 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_remove_sitesettings_mobile_dropdown_button_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_font_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_font_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='category_nav_hover_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_font_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_font_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_icon_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_link_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_header_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_header_link_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_icon_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_price_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_title_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_title_font_family',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_card_title_font_size',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать основной цвет кнопок сайта', max_length=7, verbose_name='Цвет фона кнопок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым, чтобы использовать основное скругление', null=True, verbose_name='Скругление кнопок (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать основной цвет текста кнопок', max_length=7, verbose_name='Цвет текста кнопок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать основной цвет текста сайта', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text='Оставьте пустым, чтобы использовать шрифт основного текста сайта', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым, чтобы использовать базовый размер', null=True, verbose_name='Размер шрифта (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать основной цвет кнопок.', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_hover_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать основной цвет кнопок при наведении.', max_length=7, verbose_name="Цвет фона 'В корзину' при наведении"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_text_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать основной цвет текста кнопок.', max_length=7, verbose_name="Цвет текста кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать акцентный цвет', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, чтобы использовать 5px', null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text='Оставьте пустым, чтобы использовать шрифт основного текста', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать темно-серый (#333)', max_length=7, verbose_name='Цвет фона при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать белый цвет', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='Только для адаптивного режима.', verbose_name='Схлопывать категории в иконку, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text='Только для адаптивного режима.', verbose_name='Схлопывать ссылки в подвале, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать глобальный цвет', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, чтобы использовать размер по умолчанию', null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('full', 'Иконки и полный текст'), ('partial', 'Иконки и короткий текст'), ('icons', 'Только иконки')], default='partial', help_text='Только для адаптивного режима.', max_length=10, verbose_name='Отображение ссылок в шапке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктоpe (адаптивно)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, help_text='Только для адаптивного режима.', verbose_name='Кол-во товаров в ряду'),
        ),
    ]
