# Generated by Django 5.2.8 on 2025-11-18 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_remove_sitesettings_category_nav_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона текста'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона'),
        ),
    ]
