# Generated by Django 5.2.8 on 2025-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_banner_background_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_hover_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name="Цвет фона 'В корзину' при наведении"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name="Цвет текста кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле', null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет фона при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле', null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет фона кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле', null=True, verbose_name='Скругление кнопок (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет текста кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text='Сброс к значению по умолчанию: очистите поле', max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле', null=True, verbose_name='Размер шрифта (px)'),
        ),
    ]
