# Generated by Django 5.2.8 on 2025-11-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_sitesettings_add_to_cart_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='all_products_text',
            field=models.CharField(default='Все товары', max_length=50, verbose_name="Текст ссылки 'Все товары'"),
        ),
    ]
