# Generated by Django 5.2.8 on 2025-11-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_sitesettings_all_products_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='font_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e53935', help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Акцентный цвет (ссылки, кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Можно указать несколько адресов через запятую.', verbose_name='Email для уведомлений'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_text_color',
            field=models.CharField(default='#333333', help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Основной цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('partial', 'Иконки и внизу текст'), ('icons', 'Только иконки')], default='partial', help_text='Только для адаптивного режима.', max_length=10, verbose_name='Отображение ссылок в шапке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктопе'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, help_text='Только для адаптивного режима.', verbose_name='Кол-во товаров в ряду'),
        ),
    ]
