# Generated by Django 5.2.8 on 2025-11-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_alter_banner_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('partial', 'Иконки и внизу текст'), ('icons_plus_cat_full', 'Иконки+Категории Фул'), ('icons', 'Только иконки')], default='partial', help_text='Только для адаптивного режима.', max_length=25, verbose_name='Отображение ссылок в шапке'),
        ),
    ]
