# Generated by Django 5.2.8 on 2025-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_alter_sitesettings_mobile_header_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='category_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text="Если пусто, используется значение 'По умолчанию'", max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_font_size',
            field=models.PositiveIntegerField(blank=True, help_text="Если пусто, используется значение 'По умолчанию'", null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='roboto', max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_font_size',
            field=models.PositiveIntegerField(default=16, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_text_color',
            field=models.CharField(default='#333333', help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text="Если пусто, используется значение 'По умолчанию'", max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_size',
            field=models.PositiveIntegerField(blank=True, help_text="Если пусто, используется значение 'По умолчанию'", null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Если пусто, используется цвет окружающего текста', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_size',
            field=models.PositiveIntegerField(blank=True, help_text='Если пусто, используется значение по умолчанию (22px)', null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_header_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text="Если пусто, используется значение 'По умолчанию'", max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_header_font_size',
            field=models.PositiveIntegerField(blank=True, help_text="Если пусто, используется значение 'По умолчанию'", null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_header_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text="Если пусто, используется значение 'По умолчанию'", max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_title_font_size',
            field=models.PositiveIntegerField(blank=True, help_text="Если пусто, используется значение 'По умолчанию'", null=True, verbose_name='Размер (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_title_text_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e53935', max_length=7, verbose_name='Акцентный цвет (кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, help_text='Если пусто, используется цвет обычной кнопки', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='base_font_size',
            field=models.PositiveIntegerField(default=16, editable=False, verbose_name='Базовый размер шрифта (устарело, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='body_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='roboto', editable=False, max_length=50, verbose_name='Шрифт для основного текста (устарело)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, help_text="Если пусто, используется 'Акцентный цвет'", max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=4, help_text='Только для адаптивного режима.', verbose_name='Схлопывать категории в иконку, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=4, help_text='Только для адаптивного режима.', verbose_name='Схлопывать ссылки в подвале, если их больше чем'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text="Если пусто, используется значение 'По умолчанию'", max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(blank=True, help_text="Если пусто, используется значение 'По умолчанию'", null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_text_color',
            field=models.CharField(default='#333333', editable=False, max_length=7, verbose_name='Основной цвет текста (устарело)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('partial', 'Иконки и внизу текст'), ('icons_plus_cat_full', 'Иконки+Категории(полная вер.)'), ('icons', 'Только иконки')], default='partial', help_text='Только для адаптивного режима.', max_length=25, verbose_name='Отображение ссылок в шапке'),
        ),
    ]
