# Generated by Django 5.2.8 on 2025-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_sitesettings_category_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e53935', help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Акцентный цвет (кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], help_text="Если пусто, используется значение 'По умолчанию'", max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет'),
        ),
    ]
