# Generated by Django 5.2.8 on 2025-11-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_sitesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon_animation_style',
            field=models.CharField(choices=[('scale', 'Увеличение (стандарт)'), ('rotate', 'Вращение'), ('bounce', 'Подпрыгивание')], default='scale', help_text='Эффект при наведении на иконки в шапке.', max_length=10, verbose_name='Стиль анимации иконок'),
        ),
    ]
