# Generated by Django 5.2.8 on 2025-11-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_sitesettings_icon_animation_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='button_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_title',
            field=models.CharField(default='Наш каталог цветов', help_text="Отображается на странице 'Все товары'", max_length=200, verbose_name='Заголовок страницы каталога'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_title_color',
            field=models.CharField(blank=True, help_text='Если пусто, используется основной цвет текста', max_length=7, verbose_name='Цвет заголовка каталога'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт заголовка каталога'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_title_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание заголовка каталога'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='heading_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание заголовков'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_view_mode',
            field=models.CharField(choices=[('text', 'В виде текста'), ('buttons', 'В виде кнопок')], default='text', help_text='Отображать пункты как простой текст или как кнопки.', max_length=20, verbose_name='Вид информации'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_header_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_title_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание'),
        ),
    ]
