# Generated by Django 5.2.8 on 2025-11-18 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_sitesettings_button_font_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='popular_title',
            field=models.CharField(default='Популярные букеты', help_text='Заголовок блока на главной странице', max_length=200, verbose_name='Заголовок (Популярные)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popular_title_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет заголовка (Популярные)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popular_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт (Популярные)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popular_title_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание (Популярные)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(default=100, help_text='0% = Прозрачные, 100% = Непрозрачные.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=95, help_text='0% = Полностью прозрачный, 100% = Полностью непрозрачный.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона'),
        ),
    ]
