# Generated by Django 5.2.8 on 2025-11-19 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_sitesettings_popular_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='mobile_view_mode',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#e53935', max_length=7, verbose_name='Акцентный цвет (кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_hover_bg_color',
            field=models.CharField(blank=True, max_length=7, verbose_name="Цвет фона 'В корзину' при наведении"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name="Цвет текста кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет фона при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_categories_threshold',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Схлопывать категории в иконку'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='collapse_footer_threshold',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Схлопывать ссылки в подвале'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет фона кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скругление кнопок (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Стиль шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер шрифта (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(default=95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_view_mode',
            field=models.CharField(choices=[('text', 'В виде текста'), ('buttons', 'В виде кнопок')], default='text', max_length=20, verbose_name='Вид информации'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_style',
            field=models.CharField(choices=[('partial', 'Иконки и внизу текст'), ('icons_plus_cat_full', 'Иконки+Категории(полная вер.)'), ('icons', 'Только иконки')], default='partial', max_length=25, verbose_name='Отображение ссылок в шапке'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктопе (адаптивный)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, verbose_name='Кол-во товаров в ряду'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], max_length=50, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_text_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет шрифта'),
        ),
    ]
