# Generated by Django 5.2.8 on 2025-11-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_remove_sitesettings_mobile_view_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_product_grid',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Как на десктопе (адаптивный от разрешения экрана)'), (1, 'Одна колонка'), (2, 'Две колонки'), (3, 'Три колонки'), (4, 'Четыре колонки')], default=2, verbose_name='Кол-во товаров в ряду'),
        ),
    ]
