# Generated by Django 5.2.8 on 2025-11-19 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_sitesettings_mobile_product_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Размер шрифта заголовков на мобильном. 100% = стандарт. Можно уменьшить до 50% или увеличить до 150%.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(150)], verbose_name='Масштаб шрифта заголовков (%)'),
        ),
    ]
