# Generated by Django 5.2.8 on 2025-11-19 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_sitesettings_mobile_font_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.SmallIntegerField(default=0, help_text='0% - стандартный размер. Ползунок влево уменьшает, вправо увеличивает шрифт.', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='Корректировка размера заголовков'),
        ),
    ]
