# Generated by Django 5.2.8 on 2025-11-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_alter_sitesettings_mobile_font_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Сброс к значению по умолчанию: очистите поле (нажмите ×)', max_length=7, verbose_name='Цвет шрифта'),
        ),
    ]
