# Generated by Django 5.2.8 on 2025-11-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_alter_sitesettings_default_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#e53935', max_length=7, verbose_name='Акцентный цвет (кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='catalog_title_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет заголовка каталога'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popular_title_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет заголовка (Популярные)'),
        ),
    ]
