# Generated by Django 5.2.8 on 2025-11-19 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_alter_sitesettings_add_to_cart_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.IntegerField(blank=True, default=0, help_text='0% - стандарт (по центру). Влево до -50%, вправо до +50%.', validators=[django.core.validators.MinValueValidator(-150), django.core.validators.MaxValueValidator(150)], verbose_name='Корректировка размера заголовков'),
        ),
    ]
