# Generated by Django 5.2.8 on 2025-11-19 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_alter_sitesettings_mobile_font_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.IntegerField(blank=True, default=0, help_text='0% - стандарт (по центру). Влево до -50%, вправо до +50%.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Корректировка размера заголовков'),
        ),
    ]
