# Generated by Django 5.2.8 on 2025-11-19 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_alter_sitesettings_mobile_dropdown_button_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.IntegerField(blank=True, default=0, help_text='0% - стандарт. Сдвигайте влево для уменьшения, вправо для увеличения.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Корректировка размера заголовков'),
        ),
    ]
