# Generated by Django 5.2.8 on 2025-11-19 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_alter_sitesettings_mobile_font_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky_all', 'Фиксировать Шапку + Категории'), ('sticky_header', 'Фиксировать только Шапку'), ('sticky_nav', 'Фиксировать только Категории')], default='normal', help_text='Выберите, какие элементы должны оставаться на экране при прокрутке.', max_length=20, verbose_name='Поведение шапки (Десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky', 'Фиксированная (всегда сверху)')], default='normal', help_text='Выберите, должна ли шапка оставаться на экране при прокрутке.', max_length=20, verbose_name='Поведение шапки (Мобильный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.IntegerField(blank=True, default=0, help_text='0% - стандарт (по центру). Влево до -50%, вправо до +50%.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Корректировка размера заголовков'),
        ),
    ]
