# Generated by Django 5.2.8 on 2025-11-19 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_sitesettings_desktop_header_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень прозрачности (Десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_header_transparent_scroll',
            field=models.BooleanField(default=False, verbose_name='Прозрачность при прокрутке (Десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень прозрачности (Мобильный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_transparent_scroll',
            field=models.BooleanField(default=False, verbose_name='Прозрачность при прокрутке (Мобильный)'),
        ),
    ]
