# Generated by Django 5.2.8 on 2025-11-19 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_sitesettings_desktop_header_scroll_opacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_scroll_opacity',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень прозрачности (Десктоп)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_scroll_opacity',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень прозрачности (Мобильный)'),
        ),
    ]
