# Generated by Django 5.2.8 on 2025-11-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_alter_sitesettings_desktop_header_scroll_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_categories_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сбросьте (крестик) для прозрачного фона.', max_length=7, verbose_name='Фон категорий (Десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_bg_color_custom',
            field=models.CharField(blank=True, default='', help_text='Сбросьте (крестик) для прозрачного фона.', max_length=7, verbose_name='Фон шапки (Мобильный)'),
        ),
    ]
