# Generated by Django 5.2.8 on 2025-11-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_sitesettings_desktop_categories_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_categories_bg_mode',
            field=models.CharField(choices=[('custom', 'Свой цвет (выбрать палитрой)'), ('transparent', 'Прозрачный (без фона)'), ('sheet', 'Фон листа сайта (Белый)'), ('header', 'Как в шапке')], default='sheet', max_length=20, verbose_name='Режим фона категорий (Десктоп)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_bg_mode',
            field=models.CharField(choices=[('custom', 'Свой цвет (выбрать палитрой)'), ('transparent', 'Прозрачный (без фона)'), ('sheet', 'Фон листа сайта (Белый)')], default='sheet', max_length=20, verbose_name='Режим фона шапки (Мобильный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_bg_color',
            field=models.CharField(blank=True, default='', help_text="Используется, если выбран режим 'Свой цвет'.", max_length=7, verbose_name='Свой цвет категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky_all', 'Фиксировать Шапку + Категории'), ('sticky_header', 'Фиксировать только Шапку'), ('sticky_nav', 'Фиксировать только Категории')], default='normal', max_length=20, verbose_name='Поведение шапки (Десктоп)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky', 'Фиксированная (всегда сверху)')], default='normal', max_length=20, verbose_name='Поведение шапки (Мобильный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_bg_color_custom',
            field=models.CharField(blank=True, default='', help_text="Используется, если выбран режим 'Свой цвет'.", max_length=7, verbose_name='Свой цвет шапки'),
        ),
    ]
