# Generated by Django 5.2.8 on 2025-11-19 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_sitesettings_desktop_categories_bg_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_categories_opacity',
            field=models.FloatField(blank=True, default=100, help_text='100% = Непрозрачный, 0% = Прозрачный. Работает с выбранным цветом.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность категорий (Десктоп)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky_all', 'Фиксировать Шапку + Категории'), ('sticky_header', 'Фиксировать только Шапку'), ('sticky_nav', 'Фиксировать только Категории')], default='normal', help_text='Выберите, какие элементы должны оставаться на экране при прокрутке.', max_length=20, verbose_name='Поведение шапки (Десктоп)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_scroll_opacity',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень прозрачности скролла (Десктоп)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky', 'Фиксированная (всегда сверху)')], default='normal', help_text='Выберите, должна ли шапка оставаться на экране при прокрутке.', max_length=20, verbose_name='Поведение шапки (Мобильный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_bg_color_custom',
            field=models.CharField(blank=True, default='', help_text='Сбросьте (крестик) для прозрачного фона.', max_length=7, verbose_name='Фон шапки (Мобильный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_scroll_opacity',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень прозрачности скролла (Мобильный)'),
        ),
    ]
