# Generated by Django 5.2.8 on 2025-11-20 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_sitesettings_desktop_categories_opacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='desktop_header_transparent_scroll',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_category_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0-20px', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие Категорий (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_category_scroll_enabled',
            field=models.BooleanField(default=False, verbose_name='Прозрачность Категорий при скролле'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_header_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0-20px', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие Шапки (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='desktop_header_scroll_enabled',
            field=models.BooleanField(default=False, verbose_name='Прозрачность Шапки при скролле'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_header_blur',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_sheet_bg_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Сбросьте (крестик) для прозрачного фона (будет видно общее фото).', max_length=7, verbose_name='Фон листа сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_sheet_opacity',
            field=models.FloatField(blank=True, default=95, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность листа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Свой цвет Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_bg_mode',
            field=models.CharField(choices=[('custom', 'Свой цвет (выбрать палитрой)'), ('sheet', 'Фон листа сайта'), ('header', 'Как в шапке')], default='sheet', max_length=20, verbose_name='Режим фона Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_opacity',
            field=models.FloatField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky_all', 'Фиксировать Шапку + Категории'), ('sticky_header', 'Фиксировать только Шапку'), ('sticky_nav', 'Фиксировать только Категории')], default='normal', max_length=20, verbose_name='Поведение (Десктоп)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность Шапки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.IntegerField(blank=True, default=0, help_text='0% - стандарт. Сдвигайте влево для уменьшения, вправо для увеличения.', validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Корректировка размера заголовков'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_behavior',
            field=models.CharField(choices=[('normal', 'Обычная (скрывается при прокрутке)'), ('sticky', 'Фиксированная (всегда сверху)')], default='normal', max_length=20, verbose_name='Поведение (Мобильный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_bg_color_custom',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Свой цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_bg_mode',
            field=models.CharField(choices=[('custom', 'Свой цвет (выбрать палитрой)'), ('sheet', 'Фон листа сайта')], default='sheet', max_length=20, verbose_name='Режим фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_transparent_scroll',
            field=models.BooleanField(default=False, verbose_name='Прозрачность при скролле'),
        ),
    ]
