# Generated by Django 5.2.8 on 2025-11-20 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_remove_sitesettings_desktop_header_transparent_scroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_sheet_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Эффект матового стекла', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие фона листа (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_bg_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Сбросьте (крестик) для прозрачного фона.', max_length=7, verbose_name='Фон листа сайта'),
        ),
    ]
