# Generated by Django 5.2.8 on 2025-11-20 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0079_sitesettings_site_sheet_blur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Полностью круглые края)'), ('soft', 'Soft UI (Мягкие тени, неоморфизм)'), ('3d', '3D Эффект (Выпуклые, нажимаются)'), ('gradient', 'Градиент (Современный перелив)')], default='standard', help_text='Выберите общий вид кнопок. Цвета и шрифты будут применены поверх выбранного стиля.', max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=45, help_text='0% - прозрачный, 100% - черный фон.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона текста'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='font_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#e53935', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Акцентный цвет (кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name="Цвет фона кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_hover_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name="Цвет фона 'В корзину' при наведении"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='add_to_cart_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name="Цвет текста кнопки 'В корзину'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Если пусто, используется значение из пресета.', null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет фона при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='catalog_title_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет заголовка каталога'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Свой цвет Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_categories_opacity',
            field=models.FloatField(blank=True, default=100, help_text='0% - полностью прозрачный, 100% - полностью непрозрачный.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность Категорий'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_category_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0px - нет размытия. Увеличивайте для эффекта матового стекла.', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие Категорий (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0px - нет размытия. Увеличивайте для эффекта матового стекла.', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие Шапки (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='desktop_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, help_text='0% - полностью прозрачный, 100% - полностью непрозрачный.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность Шапки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет фона кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(blank=True, default=100, help_text='0% - полностью прозрачный, 100% - полностью непрозрачный.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста кнопок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_opacity',
            field=models.FloatField(blank=True, default=95, help_text='0% - полностью прозрачный, 100% - полностью непрозрачный.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_bg_color_custom',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Свой цвет'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0px - нет размытия. Увеличивайте для эффекта матового стекла.', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_header_scroll_opacity',
            field=models.FloatField(blank=True, default=90, help_text='0% - полностью прозрачный, 100% - полностью непрозрачный.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popular_title_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет заголовка (Популярные)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_bg_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре). Если очистить, фон будет прозрачным.', max_length=7, verbose_name='Фон листа сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_blur',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0px - нет размытия. Увеличивайте для эффекта матового стекла.', null=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Размытие фона листа (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_sheet_opacity',
            field=models.FloatField(blank=True, default=95, help_text='0% - полностью прозрачный, 100% - полностью непрозрачный.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность листа'),
        ),
    ]
