# Generated by Django 5.2.8 on 2025-11-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0080_sitesettings_button_style_preset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text="Работает в режиме 'Стандарт' или для переопределения других стилей.", null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Полностью круглые края)'), ('soft', 'Soft UI (Мягкие тени, неоморфизм)'), ('3d', '3D Эффект (Выпуклые, нажимаются)'), ('gradient', 'Градиент (Перелив от Фона кнопки к Акцентному)')], default='standard', help_text="Выберите общий стиль. Для градиента будет использован 'Цвет фона' и 'Акцентный цвет'.", max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
    ]
