# Generated by Django 5.2.8 on 2025-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_alter_sitesettings_button_border_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text="Работает в режиме 'Стандарт'. Для других режимов может переопределять их стиль.", null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Круглые края)'), ('soft', 'Soft UI (Неоморфизм, мягкие тени)'), ('3d', '3D Эффект (Выпуклые)'), ('gradient', 'Градиент (Перелив Фон -> Акцент)'), ('glass', 'Стекло (Glassmorphism, полупрозрачные)'), ('neon', 'Неон (Свечение)'), ('brutal', 'Брутализм (Жесткие черные тени)')], default='standard', help_text="Выберите стиль. <b>Градиент</b> использует 'Цвет фона' и 'Акцентный цвет'.", max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
    ]
