# Generated by Django 5.2.8 on 2025-11-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_alter_sitesettings_button_border_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Круглые края)'), ('soft', 'Soft UI (Неоморфизм, мягкие тени)'), ('gradient', 'Градиент (Яркий перелив + Анимация)'), ('glass_frosted', 'Матовое стекло (Frosted Glass)'), ('neon_pulse', 'Неон Пульс (Свечение + Анимация)'), ('brutal', 'Брутализм (Жесткие черные тени)')], default='standard', help_text="Выберите общий стиль. <b>Градиент</b> использует 'Цвет фона' и 'Акцентный цвет'.", max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
    ]
