# Generated by Django 5.2.8 on 2025-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_alter_sitesettings_button_style_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, verbose_name="Текст 'О нас'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_text',
            field=models.TextField(blank=True, verbose_name='Инфо об оплате'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Отображается на странице Контакты', verbose_name='Адрес самовывоза'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_text',
            field=models.TextField(blank=True, verbose_name='Договор оферты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(blank=True, help_text='Например: Пн-Вс 09:00 - 21:00', max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#e53935', help_text='Основной цвет кнопок, ссылок и свечения Неона.', max_length=7, verbose_name='Акцентный цвет (кнопки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Основной цвет кнопки (или первый цвет градиента).', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Круглые края)'), ('soft', 'Soft UI (Неоморфизм, мягкие тени)'), ('gradient', 'Градиент (Перелив Фон -> Акцент)'), ('glass_frosted', 'Матовое стекло (Frosted Glass)'), ('neon_pulse', 'Неон Пульс (Свечение + Анимация)'), ('brutal', 'Брутализм (Жесткие черные тени)')], default='standard', help_text="Выберите общий стиль. <b>Градиент</b> использует 'Цвет фона' и 'Акцентный цвет'.", max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
    ]
