# Generated by Django 5.2.8 on 2025-11-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_sitesettings_about_text_sitesettings_payment_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='payment_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='terms_text',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_accent_color',
            field=models.CharField(blank=True, default='', help_text='Используется для Неона и Градиента. Если пусто, берется глобальный акцентный цвет.', max_length=7, verbose_name='Акцентный цвет КНОПОК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#e53935', help_text='Цвет ссылок, цен и важных элементов.', max_length=7, verbose_name='Акцентный цвет (Глобальный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Переопределяет скругление пресета.', null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Круглые края)'), ('soft', 'Soft UI (Неоморфизм, мягкие тени)'), ('gradient', 'Градиент (Яркий перелив + Анимация)'), ('glass_frosted', 'Матовое стекло (Frosted Glass)'), ('neon_pulse', 'Неон Пульс (Свечение + Анимация)'), ('brutal', 'Брутализм (Жесткие черные тени)')], default='standard', help_text="Выберите общий стиль. Градиент использует 'Цвет фона' и 'Акцентный цвет кнопок'.", max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', help_text='Для горизонтального меню категорий.', max_length=50, verbose_name='Шрифт (Меню категорий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (Меню категорий, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание (Меню категорий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста (Меню категорий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='roboto', help_text='Применяется к обычному тексту на сайте.', max_length=50, verbose_name='Шрифт (Основной текст)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_font_size',
            field=models.PositiveIntegerField(default=16, verbose_name='Размер (Основной текст, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_text_color',
            field=models.CharField(blank=True, default='#333333', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет шрифта (Основной)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', help_text='Для ссылок и текста в самом низу сайта.', max_length=50, verbose_name='Шрифт (Подвал/Footer)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (Подвал, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание (Подвал)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста (Подвал)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='montserrat', help_text='Используется для основных заголовков страниц.', max_length=50, verbose_name='Шрифт для заголовков (H1, H2...)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет иконок (Шапка)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер иконок (Шапка, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', help_text='Шрифт названия магазина в шапке.', max_length=50, verbose_name='Шрифт (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (Логотип, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', help_text="Заголовки 'Состав', 'Описание' на странице товара.", max_length=50, verbose_name='Шрифт (Заголовки описания)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (Заголовки описания, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='bold', max_length=20, verbose_name='Начертание (Заголовки описания)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста (Заголовки описания)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', help_text='Для заголовков в карточках товаров.', max_length=50, verbose_name='Шрифт (Название товара)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер (Название товара, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_style',
            field=models.CharField(choices=[('normal', 'Обычный'), ('bold', 'Жирный'), ('italic', 'Курсив')], default='normal', max_length=20, verbose_name='Начертание (Название товара)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_text_color',
            field=models.CharField(blank=True, default='', help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста (Название товара)'),
        ),
    ]
