# Generated by Django 5.2.8 on 2025-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_remove_sitesettings_about_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_secondary',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон (Дополнительный)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_address_title',
            field=models.CharField(default='Адрес для самовывоза:', max_length=100, verbose_name="Заголовок 'Адрес'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_hours_title',
            field=models.CharField(default='График работы:', max_length=100, verbose_name="Заголовок 'График'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_page_title',
            field=models.CharField(default='Контактная информация', max_length=100, verbose_name='Заголовок страницы контактов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_phone_title',
            field=models.CharField(default='Телефон для связи:', max_length=100, verbose_name="Заголовок 'Телефон'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Меню категорий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Подвал/Footer)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='montserrat', help_text='Используется для заголовков страниц.', max_length=50, verbose_name='Шрифт для заголовков (H1, H2...)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Заголовки описания)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Название товара)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.TextField(blank=True, help_text='Каждый день с новой строки', verbose_name='Режим работы'),
        ),
    ]
