# Generated by Django 5.2.8 on 2025-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_sitesettings_map_embed_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='heading_font_size',
            field=models.PositiveIntegerField(blank=True, default=24, help_text='Базовый размер для главных заголовков (H1).', null=True, verbose_name='Размер заголовков (H1, px)'),
        ),
    ]
