# Generated by Django 5.2.8 on 2025-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_sitesettings_heading_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='map_embed_code',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Фон ВСЕХ кнопок в меню (Найти, Вход, Выход). Очистите, чтобы использовать цвет десктопа.', max_length=7, verbose_name='Цвет фона кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, default='', help_text='Текст ВСЕХ кнопок в меню. Очистите, чтобы использовать цвет десктопа.', max_length=7, verbose_name='Цвет текста кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, default='', help_text='Цвет ВСЕХ ссылок и текста в меню. Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста (ВСЕ)'),
        ),
    ]
