# Generated by Django 5.2.8 on 2025-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_remove_sitesettings_map_embed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Если задан, применяется КО ВСЕМ кнопкам. Если пусто — берется десктопный.', max_length=7, verbose_name='Цвет фона кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, default='', help_text='Если задан, применяется КО ВСЕМ кнопкам. Если пусто — берется десктопный.', max_length=7, verbose_name='Цвет текста кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, default='', help_text='Цвет ВСЕХ ссылок и текста в меню. Если пусто — десктопный/черный.', max_length=7, verbose_name='Цвет текста (ВСЕ)'),
        ),
    ]
