# Generated by Django 5.2.8 on 2025-11-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_alter_sitesettings_mobile_dropdown_button_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_button_override_global',
            field=models.BooleanField(default=False, help_text="Если включено, цвета из 'Настройки выпадающих меню' будут применены ко всем кнопкам на сайте в мобильной версии (включая карточки товаров, страницы и т.д.).", verbose_name='Применить мобильные цвета ко ВСЕМ кнопкам (глобально)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Круглые края)'), ('soft', 'Soft UI (Неоморфизм, мягкие тени)'), ('gradient', 'Градиент (Яркий перелив + Анимация)'), ('glass_frosted', 'Матовое стекло (Frosted Glass)'), ('neon_pulse', 'Неон Пульс (Свечение + Анимация)'), ('brutal', 'Брутализм (Жесткие черные тени)'), ('pushable_3d', '3D Нажатие (Эффект нажатия)'), ('shine_hover', 'Блеск (Перелив при наведении)'), ('outline_fill', 'Контур (Заливка при наведении)')], default='standard', help_text="Выберите общий стиль. Градиент использует 'Цвет фона' и 'Акцентный цвет кнопок'.", max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Фон всех кнопок меню. Крестик = Сброс на цвет из десктопной версии.', max_length=7, verbose_name='Цвет фона кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, default='', help_text='Текст всех кнопок меню. Крестик = Сброс на цвет из десктопной версии.', max_length=7, verbose_name='Цвет текста кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, default='', help_text='Цвет ВСЕХ ссылок и текста в меню. Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет текста (ВСЕ)'),
        ),
    ]
