# Generated by Django 5.2.8 on 2025-11-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_sitesettings_mobile_button_override_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_icon_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет иконок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_link_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет ссылок (телефоны)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_link_hover_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет ссылок при наведении'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_subtitle_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет подзаголовков H3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_title_color',
            field=models.CharField(blank=True, help_text='Сброс к значению по умолчанию: очистите поле (нажмите × в палитре).', max_length=7, verbose_name='Цвет заголовков H1'),
        ),
    ]
