# Generated by Django 5.2.8 on 2025-11-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0092_sitesettings_static_page_icon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text="Вставьте сюда код виджета с Яндекс.Карт или Google Maps. Рекомендуемый размер: 'Растянуть по ширине'. Если поле пустое, карта не будет отображаться.", verbose_name="HTML-код карты для страницы 'Контакты'"),
        ),
    ]
