# Generated by Django 5.2.8 on 2025-11-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_sitesettings_map_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='slider_effect',
            field=models.CharField(choices=[('slide', 'Пролистывание (Slide)'), ('fade', 'Наплыв (Fade)'), ('cube', '3D Куб (Cube)'), ('flip', '3D Переворот (Flip)'), ('coverflow', '3D Карусель (Coverflow)'), ('cards', 'Карточки (Стопкой)'), ('creative_one', 'Креативный (Перспектива)'), ('creative_two', 'Креативный (Сдвиг справа)'), ('creative_three', 'Креативный (Вращение)')], default='slide', max_length=20, verbose_name='Эффект'),
        ),
    ]
