# Generated by Django 5.2.8 on 2025-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0094_alter_sitesettings_slider_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_icon_color',
            field=models.CharField(blank=True, help_text='Иконки рядом с подзаголовками. Если пусто, используется акцентный цвет сайта.', max_length=7, verbose_name='Цвет иконок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_link_color',
            field=models.CharField(blank=True, help_text='Цвет кликабельных телефонов. Если пусто, используется основной цвет текста.', max_length=7, verbose_name='Цвет ссылок (телефоны)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_link_hover_color',
            field=models.CharField(blank=True, help_text='Цвет телефонов при наведении курсора. Если пусто, используется акцентный цвет сайта.', max_length=7, verbose_name='Цвет ссылок при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_subtitle_color',
            field=models.CharField(blank=True, help_text="Заголовки блоков ('Адрес', 'График работы'). Если пусто, используется акцентный цвет сайта.", max_length=7, verbose_name='Цвет подзаголовков H3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_title_color',
            field=models.CharField(blank=True, help_text="Главный заголовок страницы ('Контакты', 'О нас'). Если пусто, используется цвет заголовков из глобальных настроек.", max_length=7, verbose_name='Цвет заголовков H1'),
        ),
    ]
