# Generated by Django 5.2.8 on 2025-11-20 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_alter_sitesettings_static_page_icon_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Свежие цветы, Быстрая доставка', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Текст, который появится при наведении (необязательно)', verbose_name='Описание (всплывашка)')),
                ('icon_svg', models.TextField(help_text='Вставьте сюда полный код <svg>...</svg> для иконки.', verbose_name='SVG иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Преимущество (в карточке)',
                'verbose_name_plural': 'Преимущества (в карточке)',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_button_size',
            field=models.CharField(choices=[('small', 'Компактные'), ('medium', 'Средние (Стандарт)'), ('large', 'Крупные (На всю ширину)')], default='medium', help_text="Влияет на размер кнопки 'В корзину' и селектора количества.", max_length=10, verbose_name='Размер кнопок в карточке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='product_image_zoom_factor',
            field=models.FloatField(default=1.5, help_text='1.0 - нет увеличения, 1.5 - среднее, 3.0 - сильное.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='Коэффициент увеличения фото (Зум)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#e53935', max_length=7, verbose_name='Акцентный цвет (Глобальный)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_accent_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Акцентный цвет КНОПОК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_radius',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Скругление углов (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_style_preset',
            field=models.CharField(choices=[('standard', 'Стандарт (Плоские, слегка скругленные)'), ('pill', 'Таблетка (Круглые края)'), ('soft', 'Soft UI (Неоморфизм, мягкие тени)'), ('gradient', 'Градиент (Яркий перелив + Анимация)'), ('glass_frosted', 'Матовое стекло (Frosted Glass)'), ('neon_pulse', 'Неон Пульс (Свечение + Анимация)'), ('brutal', 'Брутализм (Жесткие черные тени)'), ('pushable_3d', '3D Нажатие (Эффект нажатия)'), ('shine_hover', 'Блеск (Перелив при наведении)'), ('outline_fill', 'Контур (Заливка при наведении)')], default='standard', max_length=20, verbose_name='Стиль кнопок (Пресет)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='catalog_title',
            field=models.CharField(default='Наш каталог цветов', max_length=200, verbose_name='Заголовок страницы каталога'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='category_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Меню категорий)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='roboto', max_length=50, verbose_name='Шрифт (Основной текст)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Подвал/Footer)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='montserrat', max_length=50, verbose_name='Шрифт для заголовков (H1, H2...)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_size',
            field=models.PositiveIntegerField(blank=True, default=24, null=True, verbose_name='Размер заголовков (H1, px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Вставьте сюда код виджета с Яндекс.Карт или Google Maps.', verbose_name="HTML-код карты для страницы 'Контакты'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_button_override_global',
            field=models.BooleanField(default=False, verbose_name='Применить мобильные цвета ко ВСЕМ кнопкам'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет фона кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_text_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста кнопок (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_font_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет текста (ВСЕ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_font_scale',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Корректировка размера заголовков'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popular_title',
            field=models.CharField(default='Популярные букеты', max_length=200, verbose_name='Заголовок (Популярные)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_header_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Заголовки описания)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='product_title_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', max_length=50, verbose_name='Шрифт (Название товара)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_icon_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет иконок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_link_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет ссылок (телефоны)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_link_hover_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет ссылок при наведении'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_subtitle_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет подзаголовков H3'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='static_page_title_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Цвет заголовков H1'),
        ),
    ]
