# Generated by Django 5.2.8 on 2025-11-20 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0096_benefit_sitesettings_product_button_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='product_image_zoom_factor',
            field=models.FloatField(default=2.0, help_text='1.0 - нет увеличения, 2.0 - в 2 раза, 10.0 - в 10 раз.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Коэффициент увеличения фото (Зум)'),
        ),
    ]
