# Generated by Django 5.2.8 on 2025-11-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_alter_sitesettings_product_image_zoom_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_button_size',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='product_image_zoom_factor',
        ),
    ]
