# Generated by Django 5.2.8 on 2025-11-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0098_remove_sitesettings_product_button_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='postcards/', verbose_name='Изображение открытки')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (0 = бесплатно)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Открытка',
                'verbose_name_plural': 'Открытки (для заказа)',
                'ordering': ['order', 'price'],
            },
        ),
    ]
