# Generated by Django 5.2.8 on 2025-11-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0099_postcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['order'], 'verbose_name': 'Преимущество (в карточке)', 'verbose_name_plural': 'Преимущества (иконка в карточке Товара)'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_animation_style',
            field=models.CharField(choices=[('scale', 'Увеличение (стандарт)'), ('rotate', 'Вращение'), ('bounce', 'Подпрыгивание'), ('shake', 'Тряска (Shake)'), ('pulse', 'Пульсация (Pulse)'), ('swing', 'Качание (Swing)')], default='scale', help_text='Эффект при наведении на иконки в шапке.', max_length=10, verbose_name='Стиль анимации иконок'),
        ),
    ]
