# Generated by Django 5.2.8 on 2025-11-27 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0100_alter_benefit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mobile_dropdown_inherit_radius',
            field=models.BooleanField(default=True, help_text='Если галочка стоит, скругление будет таким же, как у всех кнопок на сайте. Если снята — используется значение из поля ниже.', verbose_name='Использовать глобальное скругление?'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_animation_style',
            field=models.CharField(choices=[('scale', 'Увеличение (стандарт)'), ('rotate', 'Вращение'), ('bounce', 'Подпрыгивание'), ('shake', 'Тряска (Shake)'), ('pulse', 'Пульсация (Pulse)'), ('swing', 'Качание (Swing)')], default='scale', help_text='Эффект при наведении на иконки в шапке.', max_length=10, verbose_name='СТИЛЬ АНИМАЦИИ ИКОНОК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_border_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Сработает, только если галочка слева снята.', null=True, verbose_name='Скругление кнопок (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_opacity',
            field=models.FloatField(blank=True, default=100, help_text='100% - непрозрачные, 0% - полностью прозрачные.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность кнопок'),
        ),
    ]
