# Generated by Django 5.2.8 on 2025-11-27 13:46

from django.db import migrations

def create_contacts(apps, schema_editor):
    # Получаем модель FooterPage (так правильно делать внутри миграций)
    FooterPage = apps.get_model('shop', 'FooterPage')

    # Проверяем, есть ли уже такая страница, чтобы не создавать дубликаты
    if not FooterPage.objects.filter(slug='contacts').exists():
        FooterPage.objects.create(
            title='Контакты',      # Название в меню
            slug='contacts',       # ВАЖНО: именно contacts
            order=100,             # Порядок (в конец списка)
            content='Эта страница системная. Контент берется из Настроек сайта.' # Заглушка
        )

def remove_contacts(apps, schema_editor):
    # Функция отката (если вдруг захочешь отменить миграцию)
    FooterPage = apps.get_model('shop', 'FooterPage')
    FooterPage.objects.filter(slug='contacts').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0102_alter_sitesettings_static_page_icon_color_and_more'),
    ]

    operations = [
        migrations.RunPython(create_contacts, remove_contacts),
    ]
