# Generated by Django 5.2.8 on 2025-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0103_create_contacts_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Если загрузить картинку, она заменит текстовое название и стандартную иконку.', null=True, upload_to='logo/', verbose_name='Логотип (Изображение)'),
        ),
    ]
