# Generated by Django 5.2.8 on 2025-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0104_sitesettings_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='button_accent_color',
            field=models.CharField(blank=True, default='', help_text='Важно! Этот цвет используется для обводки, эффектов наведения (hover) и теней в некоторых стилях кнопок.', max_length=7, verbose_name='Акцентный цвет КНОПОК'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font_family',
            field=models.CharField(choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='montserrat', help_text='Влияет на все крупные заголовки на сайте.', max_length=50, verbose_name='Шрифт для заголовков (H1, H2...)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_font_family',
            field=models.CharField(blank=True, choices=[('roboto', 'Стандартный (Roboto)'), ('montserrat', 'Современный (Montserrat)'), ('open-sans', 'Дружелюбный (Open Sans)'), ('lora', 'Элегантный (Lora)'), ('merriweather', 'Классический (Merriweather)'), ('playfair-display', 'Журнальный (Playfair Display)'), ('lobster', 'Декоративный (Lobster)'), ('pacifico', 'Мягкий (Pacifico)')], default='', help_text='Шрифт только для названия магазина в шапке.', max_length=50, verbose_name='Шрифт (Логотип)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_dropdown_button_bg_color',
            field=models.CharField(blank=True, default='', help_text='Если пусто, используется глобальный цвет.', max_length=7, verbose_name='Цвет фона кнопок (ВСЕ)'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
