# Generated by Django 5.2.8 on 2025-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0105_alter_sitesettings_button_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
