# Generated by Django 5.2.8 on 2025-11-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sku_start_number',
            field=models.PositiveIntegerField(default=11287, help_text='Если товаров нет, отсчет начнется с этого числа. Если товары есть, будет +1 к последнему.', verbose_name='Начальный номер артикула'),
        ),
    ]
