# Generated by Django 5.2.8 on 2025-11-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_sitesettings_sku_start_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='static_page_icon_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='static_page_link_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='static_page_link_hover_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='static_page_subtitle_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='static_page_title_color',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_start_number',
            field=models.PositiveIntegerField(default=1, help_text='Новые заказы будут начинаться с этого числа (если оно больше текущего максимального номера заказа).', verbose_name='Начальный номер ЗАКАЗА'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sku_start_number',
            field=models.PositiveIntegerField(default=11287, help_text='Если товаров нет, отсчет начнется с этого числа. Если товары есть, будет использовано (Последний Артикул + 1).', verbose_name='Начальный АРТИКУЛ товара'),
        ),
    ]
