# Generated by Django 5.2.8 on 2025-11-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_remove_sitesettings_static_page_icon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_icon_color',
            field=models.CharField(blank=True, help_text='Цвет SVG иконок (телефон, маркер карты, часы) на странице контактов.', max_length=7, verbose_name='Цвет иконок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_link_color',
            field=models.CharField(blank=True, help_text='Цвет кликабельных элементов (номера телефонов, email).', max_length=7, verbose_name='Цвет ссылок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_link_hover_color',
            field=models.CharField(blank=True, help_text='В какой цвет окрашивается ссылка, когда на неё наводят мышку.', max_length=7, verbose_name='Цвет ссылок при наведении'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_subtitle_color',
            field=models.CharField(blank=True, help_text="Цвет заголовков блоков (например, 'Адрес', 'Телефон', 'Режим работы').", max_length=7, verbose_name='Цвет подзаголовков H3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='static_page_title_color',
            field=models.CharField(blank=True, help_text="Меняет цвет заголовков на страницах 'Контакты', 'О нас' и текстовых страницах.", max_length=7, verbose_name='Цвет заголовков H1'),
        ),
    ]
