# Generated by Django 5.2.8

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        # Зависимость от миграции, где была создана модель Postcard.
        # Если makemigrations написал '0099_postcard', оставляем так.
        # Если будет ошибка, посмотрите точное название файла в shop/migrations/
        ('shop', '0099_postcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_with_card', to='shop.postcard', verbose_name='Открытка'),
        ),
        migrations.AddField(
            model_name='order',
            name='postcard_text',
            field=models.TextField(blank=True, verbose_name='Текст открытки'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_postcard_image',
            field=models.ImageField(blank=True, upload_to='orders/postcards/', verbose_name='Своё фото открытки'),
        ),
    ]