# Generated by Django 5.2.8

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        # Добавляем ТОЛЬКО поля получателя (их точно нет)
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон получателя'),
        ),
    ]