# Generated by Django 5.2.8 on 2025-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
