# Generated by Django 4.2 on 2025-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='asap', help_text="Выбранный интервал или 'Как можно быстрее'", max_length=50, verbose_name='Время доставки'),
        ),
    ]
