# Generated by Django 5.2.8 on 2025-11-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_custom_postcard_image_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('09-12', '09:00 - 12:00'), ('12-15', '12:00 - 15:00'), ('15-18', '15:00 - 18:00'), ('18-21', '18:00 - 21:00'), ('any', 'В любое время')], default='any', max_length=20, verbose_name='Время доставки'),
        ),
    ]
