# Generated by Django 5.2.8 on 2025-11-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=10, verbose_name='Способ получения'),
        ),
    ]
