# Generated by Django 4.2 on 2025-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_postcard_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена печати фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='asap', help_text="Выбранный интервал или 'asap'", max_length=50, verbose_name='Время доставки'),
        ),
    ]
