# Generated by Django 4.2 on 2025-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_custom_postcard_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_postcard_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='asap', help_text="Выбранный интервал или 'Как можно быстрее'", max_length=50, verbose_name='Время доставки'),
        ),
    ]
