# Generated by Django 5.2.8 on 2025-11-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_one_click',
            field=models.BooleanField(default=False, verbose_name='Заказ в 1 клик'),
        ),
    ]
