# Generated by Django 4.2 on 2025-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_custom_postcard_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcard_final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена открытки на момент оформления заказа', max_digits=10, verbose_name='Финальная цена открытки'),
        ),
    ]
